name: long-running-workflow
on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  long-running-job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Run curl
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${GITHUB_REPOSITORY}/commits/${GITHUB_SHA}/check-runs
      - name: hello
        run: sleep 3600
