name: long-running-workflow
on:
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  long-running-job:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: hello
        run: sleep 3600
