name: test-spot
on:
  push:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
          echo IMAGE_TAG=$(echo "$GITHUB_REF_NAME") >> $GITHUB_ENV
          echo $IMAGE_TAG
          echo "Docker image will be published with the tag: ${{ env.IMAGE_TAG }} $IMAGE_TAG!"
      - name: my-step2
        run: |
          echo ${{ env.IMAGE_TAG }}
          echo $IMAGE_TAG
