name: test-spot-gcp
on:
  push:
  merge_group:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test-spot-gcp:
    runs-on: actions-runner-controller
    container: 
      image: paritytech/ci-unified:bullseye-1.73.0-2023-11-01-v20231025
    steps:
      #- name: Sleep for 10s
      #  uses: juliangruber/sleep-action@v2.0.0
      #  with:
      #    time: 60s
      - name: my-step
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "job1"
          env
          sleep 300
      - name: my-step2
        run: |
          echo "job1"
          env
          sleep 300

