name: test-spot
on:
  push:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  job1:
    runs-on: actions-runner-controller
    steps:
      - name: my-step
        run: |
          sleep 300
